[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "a40f51fd288579f98e42fd6f15a02a79ef2f148c"
os = "macos"

    [[Graphite2.download]]
    sha256 = "4025d5cb3dbbba37349804060c40973fac5fbd2c43d826eee737f8b97fd10134"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.x86_64-apple-darwin14.tar.gz"
[[Graphite2]]
arch = "i686"
git-tree-sha1 = "f1b34952c826d71e99ad4ab000948a2b4980ad99"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "6acaaf67f7eecac4c035165660833f9de921e7d56a1c3e199012b1be10a80219"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.i686-linux-gnu.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "a40b255e12e45cb6cbb3e65c26a38517df5966b3"
os = "freebsd"

    [[Graphite2.download]]
    sha256 = "46e1afeb5df52dc887ceb4efc0dd3ce6039233a9a00043ddcbc2093b5a5c0cfd"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.x86_64-unknown-freebsd11.1.tar.gz"
[[Graphite2]]
arch = "powerpc64le"
git-tree-sha1 = "b831b6eff11dc33980e1f104c2ea8fc21321c0f9"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "f340a9f15c8694fc4a6c40b9c5ce0b9c7284d3dd776413f4cf52ed092fa671bc"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.powerpc64le-linux-gnu.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "8459c6a7f78a27892676998c9c8d58bbc17cca7e"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "c84777e782f89b8a582fb523931f3375c86bad783cd872f166e9f39f3268c68d"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.x86_64-linux-musl.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "168ceef48f46c279afb7c7107ac2e38357c894d2"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "3b33ff128bac55362221f3e3360837787f7f608db7a66d08317d20ccb68cada7"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.x86_64-linux-gnu.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "da6d88b9271cb1e03e56c66d75a4aaf63b296507"
os = "windows"

    [[Graphite2.download]]
    sha256 = "4e73df99ea62550d8e2b6bb24399c1adba7a1f27892478f3395f73c82d1ef403"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.x86_64-w64-mingw32.tar.gz"
[[Graphite2]]
arch = "aarch64"
git-tree-sha1 = "7f311cfb6e24db8a3ee30232b8f3b4daa96a360a"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "9b9d6422f34e9fc3efe4519f960e16b0b9d5ea35482e6d78a77b8ce8a5b8f5ea"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.aarch64-linux-musl.tar.gz"
[[Graphite2]]
arch = "armv7l"
git-tree-sha1 = "24044271e585f31fff34e19e71b4514f30c50a7a"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "6adb30d8c301c664d165457db4b0893d3f78efb4a49d8425e6bea04a71fd47e4"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.arm-linux-gnueabihf.tar.gz"
[[Graphite2]]
arch = "i686"
git-tree-sha1 = "72269b67dc78883794652cbe57f99568a7790326"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "9b618d376b0fc7b7b102aaba80636e22d1d897ac42b9135ac21a77b230f442e8"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.i686-linux-musl.tar.gz"
[[Graphite2]]
arch = "armv7l"
git-tree-sha1 = "e34327da6ed74536f43380a172f66ced6014cd07"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "5762b77781827a729abdbc2a9534409b330577c483c680cb3357b7ac95c8dd2f"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.arm-linux-musleabihf.tar.gz"
[[Graphite2]]
arch = "aarch64"
git-tree-sha1 = "078e11dc4b6799ea1928d0cfe4b39d677f35d76a"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "3cc2a89c0066bab3547e8237ea9466becd1ed2587df6d7fe8c666c38f89a74ed"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.aarch64-linux-gnu.tar.gz"
[[Graphite2]]
arch = "i686"
git-tree-sha1 = "f6790d44cbb5d88c6c4953623cba154578e26be0"
os = "windows"

    [[Graphite2.download]]
    sha256 = "42db7771afd71239d0f17ee223517c7e60ec3a580d93972fdc69fe10d2bfae39"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+1/Graphite2.v1.3.13.i686-w64-mingw32.tar.gz"
